### ISSUE TITLE
Script fails to display long listing format

### ISSUE THREAD

**Issue by unjello** [jonathf/gls#1]
The script fails with:
```
    group = pwd.getpwuid(stat.st_gid).pw_name
KeyError: 'getpwuid(): uid not found: 20'
```

`20` is `staff` on macOS, but the script tries to fetch group description from password database, instead group database.

**Comment by jonathf** [comment]
I appologies, but the gls project is no longer being actively maintained.
if you want similar features, I can highly recommend the excellent exa project
https://the.exa.website

**Comment by unjello** [comment]
Thanks for the tip. Didn't now the project, but will definitely give it a try!
